packages:
  - frontend
  - tests
  - email-templates

overrides:
  cookie@<0.7.0: '>=0.7.0'
  devalue: ^5.3.2
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  valibot@>=0.31.0 <1.2.0: '>=1.2.0'
  validator@<13.15.20: '>=13.15.20'
